// Static product data from site content doc — used as fallback until DB is seeded
// Prices in dollars

export interface StaticProduct {
  id: string;
  name: string;
  slug: string;
  price: string;
  category: string;
  categorySlug: string;
  description?: string;
  image: string;
  images: string[];
  variants: { id: string; name: string }[];
  isActive: boolean;
}

const CDN = "https://cdn.campriverbend.com";

export const CATEGORIES = [
  { name: "All", slug: "all" },
  { name: "Adult Clothing", slug: "adult-clothing" },
  { name: "Boys Clothing", slug: "boys-clothing" },
  { name: "Girls Clothing", slug: "girls-clothing" },
  { name: "Accessories", slug: "accessories" },
  { name: "Backpacks", slug: "backpacks" },
];

export const PRODUCTS: StaticProduct[] = [
  {
    id: "1",
    name: "Adult Performance Dri-Fit Long Sleeve Hoodie",
    slug: "adult-dri-fit-hoodie",
    price: "25.00",
    category: "Adult Clothing",
    categorySlug: "adult-clothing",
    image: `${CDN}/2024/05/01194619/Adult-Dri-Fit-Long-Sleeve-Hoodie-scaled.jpg`,
    images: [`${CDN}/2024/05/01194619/Adult-Dri-Fit-Long-Sleeve-Hoodie-scaled.jpg`],
    variants: [
      { id: "1-as", name: "AS" },
      { id: "1-am", name: "AM" },
      { id: "1-al", name: "AL" },
      { id: "1-axl", name: "AXL" },
      { id: "1-axxl", name: "AXXL" },
    ],
    isActive: true,
  },
  {
    id: "2",
    name: "Camp Riverbend Embroidered Backpack",
    slug: "embroidered-backpack",
    price: "30.00",
    category: "Backpacks",
    categorySlug: "backpacks",
    image: `${CDN}/2024/05/01194626/Camp-Riverbend-Embroidered-Backpack-scaled.jpg`,
    images: [`${CDN}/2024/05/01194626/Camp-Riverbend-Embroidered-Backpack-scaled.jpg`],
    variants: [],
    isActive: true,
  },
  {
    id: "3",
    name: "Camp Riverbend Performance Grey Hat (Adult)",
    slug: "grey-hat-adult",
    price: "25.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/2024/05/01194647/Camp-Riverbend-Performance-Grey-Hat-Adult-scaled.jpg`,
    images: [`${CDN}/2024/05/01194647/Camp-Riverbend-Performance-Grey-Hat-Adult-scaled.jpg`],
    variants: [],
    isActive: true,
  },
  {
    id: "4",
    name: "Camp Riverbend White Hat (Adult)",
    slug: "white-hat-adult",
    price: "25.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/2024/05/01194612/Camp-Riverbend-White-Hat-Adult-scaled.jpg`,
    images: [`${CDN}/2024/05/01194612/Camp-Riverbend-White-Hat-Adult-scaled.jpg`],
    variants: [],
    isActive: true,
  },
  {
    id: "5",
    name: "Girls Ribbed Tank Tops (Red)",
    slug: "girls-ribbed-tank-red",
    price: "20.00",
    category: "Girls Clothing",
    categorySlug: "girls-clothing",
    image: `${CDN}/2024/05/01194633/Girls-Ribbed-Tank-Top-scaled.jpg`,
    images: [`${CDN}/2024/05/01194633/Girls-Ribbed-Tank-Top-scaled.jpg`],
    variants: [
      { id: "5-yl", name: "YL" },
      { id: "5-as", name: "AS" },
      { id: "5-am", name: "AM" },
      { id: "5-al", name: "AL" },
    ],
    isActive: true,
  },
  {
    id: "6",
    name: "Kids Performance Dri-Fit Short Sleeve Hoodie",
    slug: "kids-dri-fit-hoodie",
    price: "20.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/2024/05/01194641/Kids-Dri-Fit-Hoodie-scaled.jpg`,
    images: [`${CDN}/2024/05/01194641/Kids-Dri-Fit-Hoodie-scaled.jpg`],
    variants: [
      { id: "6-ys", name: "YS" },
      { id: "6-ym", name: "YM" },
      { id: "6-yl", name: "YL" },
    ],
    isActive: true,
  },
  {
    id: "7",
    name: "Camper T-Shirt",
    slug: "camper-t-shirt",
    price: "12.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2021/12/03101335/Camper-T-Shirt.jpg`,
    images: [`${CDN}/wp-content/uploads/2021/12/03101335/Camper-T-Shirt.jpg`],
    variants: [
      { id: "7-yxs", name: "YXS" },
      { id: "7-ys", name: "YS" },
      { id: "7-ym", name: "YM" },
      { id: "7-yl", name: "YL" },
    ],
    isActive: true,
  },
  {
    id: "8",
    name: "Camper Tank Top",
    slug: "camper-tank-top",
    price: "15.00",
    category: "Girls Clothing",
    categorySlug: "girls-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101319/Camper-Tank-Top.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101319/Camper-Tank-Top.jpg`],
    variants: [
      { id: "8-ys", name: "YS" },
      { id: "8-ym", name: "YM" },
      { id: "8-yl", name: "YL" },
      { id: "8-as", name: "AS" },
    ],
    isActive: true,
  },
  {
    id: "9",
    name: "Crewneck Sweatshirt (Grey)",
    slug: "crewneck-grey",
    price: "30.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101258/Crewneck-Sweatshirt-Grey.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101258/Crewneck-Sweatshirt-Grey.jpg`],
    variants: [
      { id: "9-ys", name: "YS" },
      { id: "9-ym", name: "YM" },
      { id: "9-yl", name: "YL" },
      { id: "9-yxl", name: "YXL" },
    ],
    isActive: true,
  },
  {
    id: "10",
    name: "Crewneck Sweatshirt (Red)",
    slug: "crewneck-red",
    price: "30.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101309/Crewneck-Sweatshirt-red.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101309/Crewneck-Sweatshirt-red.jpg`],
    variants: [
      { id: "10-ys", name: "YS" },
      { id: "10-ym", name: "YM" },
      { id: "10-yl", name: "YL" },
      { id: "10-yxl", name: "YXL" },
    ],
    isActive: true,
  },
  {
    id: "11",
    name: "Hooded Sweatshirt (Red)",
    slug: "hoodie-red",
    price: "30.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101254/Hooded-Sweatshirt-Red.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101254/Hooded-Sweatshirt-Red.jpg`],
    variants: [
      { id: "11-ys", name: "YS" },
      { id: "11-ym", name: "YM" },
      { id: "11-yl", name: "YL" },
      { id: "11-as", name: "AS" },
      { id: "11-am", name: "AM" },
      { id: "11-al", name: "AL" },
      { id: "11-axl", name: "AXL" },
    ],
    isActive: true,
  },
  {
    id: "12",
    name: "Hooded Sweatshirt (Grey)",
    slug: "hoodie-grey",
    price: "30.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101243/Hooded-Sweatshirt-Grey.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101243/Hooded-Sweatshirt-Grey.jpg`],
    variants: [
      { id: "12-ys", name: "YS" },
      { id: "12-ym", name: "YM" },
      { id: "12-yl", name: "YL" },
      { id: "12-as", name: "AS" },
      { id: "12-am", name: "AM" },
      { id: "12-al", name: "AL" },
      { id: "12-axl", name: "AXL" },
    ],
    isActive: true,
  },
  {
    id: "13",
    name: "Boys / Mens Shorts",
    slug: "boys-shorts",
    price: "25.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/04150704/Boys-Shorts-scaled.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/04150704/Boys-Shorts-scaled.jpg`],
    variants: [
      { id: "13-yxs", name: "YXS" },
      { id: "13-ys", name: "YS" },
      { id: "13-ym", name: "YM" },
      { id: "13-yl", name: "YL" },
      { id: "13-yxl", name: "YXL" },
      { id: "13-as", name: "AS" },
      { id: "13-am", name: "AM" },
      { id: "13-al", name: "AL" },
    ],
    isActive: true,
  },
  {
    id: "14",
    name: "Girls / Womens Shorts",
    slug: "girls-shorts",
    price: "25.00",
    category: "Girls Clothing",
    categorySlug: "girls-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101221/Girls-or-Womens-Shorts.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101221/Girls-or-Womens-Shorts.jpg`],
    variants: [
      { id: "14-ym", name: "YM" },
      { id: "14-yl", name: "YL" },
      { id: "14-as", name: "AS" },
      { id: "14-am", name: "AM" },
      { id: "14-al", name: "AL" },
      { id: "14-axl", name: "AXL" },
    ],
    isActive: true,
  },
  {
    id: "15",
    name: "Rash Guard",
    slug: "rash-guard",
    price: "30.00",
    category: "Boys Clothing",
    categorySlug: "boys-clothing",
    image: `${CDN}/wp-content/uploads/2022/01/03101228/Rash-Guard.png`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101228/Rash-Guard.png`],
    variants: [
      { id: "15-ym", name: "YM" },
      { id: "15-yl", name: "YL" },
      { id: "15-as", name: "AS" },
    ],
    isActive: true,
  },
  {
    id: "16",
    name: "Socks",
    slug: "socks",
    price: "12.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/wp-content/uploads/2022/01/03101101/Socks.jpg`,
    images: [
      `${CDN}/wp-content/uploads/2022/01/03101101/Socks.jpg`,
      `${CDN}/wp-content/uploads/2022/01/21094825/Socks-Quarter-scaled.jpg`,
    ],
    variants: [
      { id: "16-quarter", name: "Quarter" },
      { id: "16-long", name: "Long" },
      { id: "16-youth", name: "Youth" },
      { id: "16-small", name: "Small" },
      { id: "16-medium", name: "Medium" },
    ],
    isActive: true,
  },
  {
    id: "17",
    name: "Baseball Hats",
    slug: "baseball-hats",
    price: "25.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/wp-content/uploads/2022/01/03101159/Baseball-Cap-Red.jpg`,
    images: [
      `${CDN}/wp-content/uploads/2022/01/03101159/Baseball-Cap-Red.jpg`,
      `${CDN}/wp-content/uploads/2022/01/21094414/White-Hat-scaled.jpg`,
    ],
    variants: [
      { id: "17-red", name: "Red" },
      { id: "17-white", name: "White" },
    ],
    isActive: true,
  },
  {
    id: "18",
    name: "Winter Beanie",
    slug: "winter-beanie",
    price: "15.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/wp-content/uploads/2022/01/03101128/Beanie.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101128/Beanie.jpg`],
    variants: [],
    isActive: true,
  },
  {
    id: "19",
    name: "Gaga Gloves",
    slug: "gaga-gloves",
    price: "25.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/wp-content/uploads/2022/01/03101032/Gaga-Gloves-1.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/03101032/Gaga-Gloves-1.jpg`],
    variants: [
      { id: "19-ym", name: "YM" },
      { id: "19-yl", name: "YL" },
    ],
    isActive: true,
  },
  {
    id: "20",
    name: "Neck Gaiter",
    slug: "neck-gaiter",
    price: "5.00",
    category: "Accessories",
    categorySlug: "accessories",
    image: `${CDN}/wp-content/uploads/2022/01/21095812/Gaiter-scaled.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/01/21095812/Gaiter-scaled.jpg`],
    variants: [],
    isActive: true,
  },
  {
    id: "21",
    name: "Backpack",
    slug: "backpack",
    price: "30.00",
    category: "Backpacks",
    categorySlug: "backpacks",
    image: `${CDN}/wp-content/uploads/2022/06/03100827/Backpack-2.jpg`,
    images: [`${CDN}/wp-content/uploads/2022/06/03100827/Backpack-2.jpg`],
    variants: [],
    isActive: true,
  },
];

export function getProducts(categorySlug?: string) {
  let filtered = PRODUCTS.filter((p) => p.isActive);
  if (categorySlug && categorySlug !== "all") {
    filtered = filtered.filter((p) => p.categorySlug === categorySlug);
  }
  return filtered;
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug && p.isActive);
}
