export type ZoneCategory =
  | "sports"
  | "aquatics"
  | "arts"
  | "adventure"
  | "facilities"
  | "nature"
  | "gathering";

export interface MapZone {
  id: string;
  label: string;
  category: ZoneCategory;
  description: string;
  activities: string[];
  ageGroups?: string;
  learnMoreHref?: string;
  /** SVG polygon/path points for the clickable area */
  path: string;
  /** Center coordinates for label placement */
  cx: number;
  cy: number;
}

export const CATEGORY_META: Record<
  ZoneCategory,
  { label: string; color: string; bgClass: string }
> = {
  sports: { label: "Sports", color: "#DB3832", bgClass: "bg-camp-red" },
  aquatics: { label: "Aquatics", color: "#3B7EA1", bgClass: "bg-river" },
  arts: { label: "Arts", color: "#7A8F6D", bgClass: "bg-sage" },
  adventure: { label: "Adventure", color: "#2D5016", bgClass: "bg-forest" },
  facilities: { label: "Facilities", color: "#6B5B4E", bgClass: "bg-bark" },
  nature: { label: "Nature", color: "#3D6B1E", bgClass: "bg-forest-light" },
  gathering: { label: "Gathering", color: "#87CEEB", bgClass: "bg-sky" },
};

export const MAP_ZONES: MapZone[] = [
  // ── Aquatics (west side, near river) ────────────────
  {
    id: "canoe-launch",
    label: "Canoe Launch",
    category: "aquatics",
    description: "Where campers set out on river adventures. Canoes and kayaks launch from this dock area along the Passaic River.",
    activities: ["Canoeing", "Kayaking", "River exploration"],
    ageGroups: "Grades 1-8",
    path: "M40,280 L100,275 L105,310 L45,315 Z",
    cx: 72, cy: 295,
  },
  {
    id: "boat-house",
    label: "Boat House",
    category: "aquatics",
    description: "Storage and staging area for all watercraft. Equipment checks and water safety briefings happen here.",
    activities: ["Equipment storage", "Safety briefings"],
    path: "M40,320 L100,315 L105,345 L45,350 Z",
    cx: 72, cy: 332,
  },
  {
    id: "spray-park",
    label: "Spray Park",
    category: "aquatics",
    description: "A refreshing water play area with fountains, sprayers, and splash zones — perfect for cooling off on hot summer days.",
    activities: ["Water play", "Splash zones", "Cooling off"],
    ageGroups: "All ages",
    path: "M110,320 L170,315 L175,355 L115,360 Z",
    cx: 142, cy: 337,
  },

  // ── Sports (central area) ──────────────────────────
  {
    id: "basketball",
    label: "Basketball",
    category: "sports",
    description: "Full-size outdoor basketball courts for games, drills, and tournaments.",
    activities: ["Basketball games", "Skills clinics", "Tournaments"],
    ageGroups: "Grades 1-8",
    path: "M300,120 L370,115 L375,155 L305,160 Z",
    cx: 337, cy: 137,
  },
  {
    id: "tennis",
    label: "Tennis",
    category: "sports",
    description: "Multiple tennis courts for lessons and match play. Equipment provided.",
    activities: ["Tennis lessons", "Match play", "Drills"],
    ageGroups: "Grades 1-8",
    path: "M380,120 L450,115 L455,155 L385,160 Z",
    cx: 417, cy: 137,
  },
  {
    id: "soccer",
    label: "Soccer",
    category: "sports",
    description: "Large open field for soccer games, drills, and World Cup-style tournaments.",
    activities: ["Soccer games", "Drills", "Tournaments"],
    ageGroups: "Grades 1-8",
    path: "M460,120 L550,115 L555,175 L465,180 Z",
    cx: 507, cy: 147,
  },
  {
    id: "hockey",
    label: "Hockey",
    category: "sports",
    description: "Street hockey rink for fast-paced games and skills development.",
    activities: ["Street hockey", "Skills games"],
    ageGroups: "Grades 1-8",
    path: "M300,170 L370,165 L375,205 L305,210 Z",
    cx: 337, cy: 187,
  },
  {
    id: "gaga-pits",
    label: "Gaga Pits",
    category: "sports",
    description: "Multiple gaga ball pits — the camp favorite! Fast-paced, inclusive game that everyone loves.",
    activities: ["Gaga ball", "Group games"],
    ageGroups: "All ages",
    path: "M380,170 L430,167 L433,200 L383,203 Z",
    cx: 406, cy: 185,
  },
  {
    id: "mini-golf",
    label: "Mini Golf",
    category: "sports",
    description: "A fun miniature golf course right at camp. Great for friendly competition and relaxation.",
    activities: ["Mini golf", "Putting challenges"],
    ageGroups: "All ages",
    path: "M440,170 L510,167 L513,200 L443,203 Z",
    cx: 476, cy: 185,
  },
  {
    id: "human-foosball",
    label: "Human Foosball",
    category: "sports",
    description: "Life-size foosball court where campers become the players! A unique, high-energy team game.",
    activities: ["Human foosball", "Team games"],
    ageGroups: "Grades 1-8",
    path: "M520,170 L590,167 L593,200 L523,203 Z",
    cx: 556, cy: 185,
  },
  {
    id: "pedal-karts",
    label: "Pedal Karts",
    category: "sports",
    description: "Pedal-powered go-karts on a dedicated track. Racing, cruising, and loads of fun.",
    activities: ["Kart racing", "Cruising"],
    ageGroups: "Grades 1-8",
    path: "M300,215 L380,212 L383,248 L303,251 Z",
    cx: 341, cy: 231,
  },
  {
    id: "gymnastics",
    label: "Gymnastics",
    category: "sports",
    description: "Indoor and outdoor gymnastics facilities for tumbling, balance, and coordination.",
    activities: ["Tumbling", "Balance beam", "Floor exercises"],
    ageGroups: "All ages",
    path: "M600,120 L670,117 L673,160 L603,163 Z",
    cx: 636, cy: 140,
  },
  {
    id: "bocce-ball",
    label: "Bocce Ball",
    category: "sports",
    description: "Bocce ball courts for relaxed, strategic play among friends.",
    activities: ["Bocce ball"],
    ageGroups: "All ages",
    path: "M600,170 L660,167 L663,195 L603,198 Z",
    cx: 631, cy: 182,
  },
  {
    id: "wall-ball",
    label: "Wall Ball",
    category: "sports",
    description: "Wall ball courts for fast-paced handball-style games.",
    activities: ["Wall ball", "Handball"],
    ageGroups: "Grades 1-8",
    path: "M670,170 L730,167 L733,195 L673,198 Z",
    cx: 701, cy: 182,
  },

  // ── Adventure ──────────────────────────────────────
  {
    id: "zipline",
    label: "Zipline",
    category: "adventure",
    description: "Soar through the treetops on camp's thrilling zipline. Safety-harnessed and staff-supervised at all times.",
    activities: ["Ziplining"],
    ageGroups: "Grades 3-8",
    learnMoreHref: "/activities",
    path: "M150,170 L230,165 L235,200 L155,205 Z",
    cx: 192, cy: 185,
  },
  {
    id: "climbing-wall",
    label: "Climbing Wall",
    category: "adventure",
    description: "Multi-route climbing wall with varying difficulty levels. Build strength and confidence one hold at a time.",
    activities: ["Rock climbing", "Bouldering"],
    ageGroups: "Grades 1-8",
    path: "M150,210 L230,207 L233,240 L153,243 Z",
    cx: 191, cy: 225,
  },
  {
    id: "ropes-course",
    label: "Ropes Course",
    category: "adventure",
    description: "High and low ropes challenge course. Teamwork, trust, and conquering fears in a safe environment.",
    activities: ["High ropes", "Low ropes", "Team challenges"],
    ageGroups: "Grades 3-8",
    path: "M150,248 L230,245 L233,278 L153,281 Z",
    cx: 191, cy: 263,
  },
  {
    id: "mini-zipline",
    label: "Mini Zipline",
    category: "adventure",
    description: "A smaller, gentler zipline perfect for younger campers getting their first taste of adventure.",
    activities: ["Mini ziplining"],
    ageGroups: "Pre-K to Grade 2",
    path: "M240,210 L290,207 L293,240 L243,243 Z",
    cx: 266, cy: 225,
  },
  {
    id: "archery",
    label: "Archery",
    category: "adventure",
    description: "Learn to shoot with real bows and arrows on our dedicated archery range. Focus, aim, release!",
    activities: ["Archery lessons", "Target practice"],
    ageGroups: "Grades 1-8",
    path: "M240,248 L290,245 L293,278 L243,281 Z",
    cx: 266, cy: 263,
  },
  {
    id: "ninja-course",
    label: "Ninja Course",
    category: "adventure",
    description: "Inspired by obstacle course shows — swing, climb, balance, and conquer the ninja warrior course.",
    activities: ["Obstacle course", "Ninja challenges"],
    ageGroups: "Grades 1-8",
    path: "M150,285 L230,282 L233,312 L153,315 Z",
    cx: 191, cy: 298,
  },
  {
    id: "mega-course",
    label: "Mega Course",
    category: "adventure",
    description: "The ultimate obstacle course combining elements from all adventure activities. Can you complete it?",
    activities: ["Mega obstacles", "Timed challenges"],
    ageGroups: "Grades 3-8",
    path: "M240,285 L290,282 L293,312 L243,315 Z",
    cx: 266, cy: 298,
  },

  // ── Arts ────────────────────────────────────────────
  {
    id: "arts-crafts-quad",
    label: "Arts & Crafts Quad",
    category: "arts",
    description: "Outdoor creative space with covered areas for painting, drawing, ceramics, tie-dye, and more.",
    activities: ["Painting", "Drawing", "Ceramics", "Tie-dye", "Mixed media"],
    ageGroups: "All ages",
    learnMoreHref: "/activities",
    path: "M400,220 L480,217 L483,260 L403,263 Z",
    cx: 441, cy: 240,
  },
  {
    id: "the-studio",
    label: "The Studio",
    category: "arts",
    description: "Indoor art studio for music, dance, drama rehearsals, and creative workshops.",
    activities: ["Music", "Dance", "Drama", "Creative workshops"],
    ageGroups: "All ages",
    path: "M490,220 L560,217 L563,260 L493,263 Z",
    cx: 526, cy: 240,
  },
  {
    id: "open-air-theatre",
    label: "Open Air Theatre",
    category: "arts",
    description: "Amphitheatre-style performance space for camp shows, skits, and talent shows under the open sky.",
    activities: ["Performances", "Camp shows", "Talent shows"],
    ageGroups: "All ages",
    path: "M400,270 L480,267 L483,305 L403,308 Z",
    cx: 441, cy: 287,
  },

  // ── Gathering ──────────────────────────────────────
  {
    id: "campfire-circle",
    label: "Campfire Circle",
    category: "gathering",
    description: "The heart of camp traditions. Evening singalongs, s'mores, stories, and the famous Camp Riverbend spirit.",
    activities: ["Campfire songs", "S'mores", "Storytelling", "Spirit events"],
    ageGroups: "All ages",
    path: "M490,270 L560,267 L563,305 L493,308 Z",
    cx: 526, cy: 287,
  },
  {
    id: "lunch-pavilion",
    label: "Lunch Pavilion",
    category: "gathering",
    description: "Covered outdoor dining area where campers enjoy chef-prepared lunches together.",
    activities: ["Lunch", "Special meals", "Rainy day activities"],
    ageGroups: "All ages",
    learnMoreHref: "/lunch",
    path: "M570,220 L650,217 L653,260 L573,263 Z",
    cx: 611, cy: 240,
  },
  {
    id: "big-barn",
    label: "Big Barn",
    category: "gathering",
    description: "A camp landmark — large indoor space for assemblies, rainy day activities, and special events.",
    activities: ["Assemblies", "Indoor games", "Special events"],
    ageGroups: "All ages",
    path: "M570,270 L650,267 L653,305 L573,308 Z",
    cx: 611, cy: 287,
  },
  {
    id: "game-pavilion",
    label: "Game Pavilion",
    category: "gathering",
    description: "Covered area with games, GaGa, ping pong, and hangout space for campers.",
    activities: ["Table games", "Ping pong", "Hangout space"],
    ageGroups: "All ages",
    path: "M660,220 L730,217 L733,260 L663,263 Z",
    cx: 696, cy: 240,
  },
  {
    id: "auditorium",
    label: "Auditorium",
    category: "gathering",
    description: "Indoor performance and gathering space with stage for shows and presentations.",
    activities: ["Shows", "Presentations", "Movie screenings"],
    ageGroups: "All ages",
    path: "M660,270 L730,267 L733,305 L663,308 Z",
    cx: 696, cy: 287,
  },

  // ── Facilities ─────────────────────────────────────
  {
    id: "snack-shack",
    label: "Snack Shack",
    category: "facilities",
    description: "The camper favorite — cold treats, snacks, and refreshments available during free time.",
    activities: ["Snacks", "Ice cream", "Refreshments"],
    path: "M740,220 L790,218 L792,250 L742,252 Z",
    cx: 766, cy: 235,
  },
  {
    id: "camp-office",
    label: "Camp Office",
    category: "facilities",
    description: "Administrative hub and home base for the Breene family directors.",
    activities: ["Administration", "Parent check-in"],
    path: "M740,258 L790,256 L792,288 L742,290 Z",
    cx: 766, cy: 273,
  },
  {
    id: "nurses-station",
    label: "Nurse's Station",
    category: "facilities",
    description: "On-site medical facility staffed with registered nurses throughout the camp day.",
    activities: ["First aid", "Health monitoring", "Medication management"],
    learnMoreHref: "/health-safety",
    path: "M740,295 L790,293 L792,325 L742,327 Z",
    cx: 766, cy: 310,
  },
  {
    id: "chefs-kitchen",
    label: "Chef's Kitchen",
    category: "facilities",
    description: "Professional kitchen where our chefs prepare fresh, healthy lunches and snacks daily.",
    activities: ["Meal prep", "Cooking programs"],
    learnMoreHref: "/lunch",
    path: "M740,332 L790,330 L792,362 L742,364 Z",
    cx: 766, cy: 347,
  },
  {
    id: "security-entry",
    label: "Security / Entry",
    category: "facilities",
    description: "Secure entry point with check-in protocols. All visitors verified before entering campus.",
    activities: ["Check-in", "Security", "Drop-off / Pick-up"],
    learnMoreHref: "/health-safety",
    path: "M380,380 L450,378 L452,405 L382,407 Z",
    cx: 416, cy: 392,
  },

  // ── Nature ─────────────────────────────────────────
  {
    id: "nature-area",
    label: "Nature Area",
    category: "nature",
    description: "Wetlands sanctuary and nature trails where campers explore wildlife, plants, and outdoor science.",
    activities: ["Nature walks", "Wildlife observation", "Outdoor science"],
    ageGroups: "All ages",
    path: "M40,360 L130,355 L135,410 L45,415 Z",
    cx: 87, cy: 385,
  },
  {
    id: "sandbox",
    label: "Sandbox",
    category: "nature",
    description: "Large sandpit play area for building, digging, and creative outdoor play.",
    activities: ["Sand play", "Building", "Creative play"],
    ageGroups: "Pre-K to Grade 2",
    path: "M140,370 L200,367 L203,400 L143,403 Z",
    cx: 171, cy: 385,
  },

  // ── Clubhouse Zone ─────────────────────────────────
  {
    id: "clubhouse-field",
    label: "Clubhouse Field",
    category: "nature",
    description: "Dedicated outdoor play space for the youngest campers with age-appropriate activities.",
    activities: ["Outdoor play", "Field games", "Free play"],
    ageGroups: "Pre-K to Kindergarten",
    path: "M210,340 L290,337 L293,380 L213,383 Z",
    cx: 251, cy: 360,
  },
  {
    id: "legoland",
    label: "Legoland",
    category: "arts",
    description: "Dedicated LEGO building space where young campers construct, imagine, and create.",
    activities: ["LEGO building", "Creative construction"],
    ageGroups: "Pre-K to Grade 2",
    path: "M300,340 L360,337 L363,370 L303,373 Z",
    cx: 331, cy: 355,
  },
  {
    id: "the-clubhouse",
    label: "The Clubhouse",
    category: "gathering",
    description: "Home base for our youngest campers (ages 3-5). A warm, welcoming environment designed just for them.",
    activities: ["Arts & crafts", "Music", "Swimming", "Nature", "Sports"],
    ageGroups: "Pre-K to Kindergarten",
    learnMoreHref: "/clubhouse",
    path: "M210,388 L290,385 L293,420 L213,423 Z",
    cx: 251, cy: 404,
  },
];
